### ISSUE TITLE
Split tracks into purchasable and non-purchasable

### ISSUE THREAD

**Issue by TheMozg** [Yakkodash/itmo-sql-practice#1]
I think we have to add trigger for `T_ORDERS` on available tracks for purchase (artist is in the database).
@Yakkodash, what do you think?

**Comment by Yakkodash** [comment]
@TheMozg, yeah, I think we should. I guess another bridge table?

**Comment by TheMozg** [comment]
@Yakkodash, great, let's get to work then.

**Comment by TheMozg** [comment]
Seems to work great as of 2e52d0757496f9eff9c2babd353700d3d974ab44
